'use client';
import React from 'react';
import { Inter, Unica_One, Syne } from 'next/font/google';
import './components/styles/globals.scss';
import Header from './components/Header';
import Cart from './components/Cart';
import { useEffect, useState, createContext, useContext } from 'react';
import Footer from './components/Footer';

const inter = Inter({ subsets: ['latin'] });
export const unica = Unica_One({ subsets: ['latin'], weight: ['400'] });
export const syne = Syne({
    subsets: ['latin'],
    weight: ['400', '500', '600', '700', '800'],
});

const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

// export const authenticateContext = createContext(authenticate);
export default function RootLayout({ children }) {
    const [showCart, setShowCart] = useState(false);
    const [fetchTrigger, setFetchTrigger] = useState(false);
    const [authenticate, setAuthenticate] = useState(false);

    useEffect(() => {
        const token = window.localStorage.getItem('userToken');
        if (token) {
            setAuthenticate(true);
        }
    }, []);

    return (
        <html lang="en">
            <body className={inter.className}>
                <Header
                    setShowCart={setShowCart}
                    setFetchTrigger={setFetchTrigger}
                />
                <Cart
                    showCart={showCart}
                    setShowCart={setShowCart}
                    fetchTrigger={fetchTrigger}
                    setFetchTrigger={setFetchTrigger}
                />
                {React.cloneElement(children, { showCart })}
                <Footer />
            </body>
        </html>
    );
}
