'use client';
import React, { useReducer } from 'react';
import { Inter, Unica_One, Syne } from 'next/font/google';
import './components/styles/globals.scss';
import Header from './components/Header';
import Cart from './components/Cart';
import { useEffect, useState, createContext, useContext } from 'react';
import Footer from './components/Footer';

const inter = Inter({ subsets: ['latin'] });
export const unica = Unica_One({ subsets: ['latin'], weight: ['400'] });
export const syne = Syne({
    subsets: ['latin'],
    weight: ['400', '500', '600', '700', '800'],
});

const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export const pageTriggerContext = createContext(null);
export const pageTriggerDispatch = createContext(null);
export const val = true;
export function pageTriggerReducer(pageT, action) {
    switch (action.type) {
        case 'changed': {
            return !pageT;
        }
    }
}

export default function RootLayout({ children }) {
    const [showCart, setShowCart] = useState(false);
    const [fetchTrigger, setFetchTrigger] = useState(false);
    const [pageTrigger, dispatch] = useReducer(
        pageTriggerReducer,
        val ? 'true' : 'false'
    );

    return (
        <html lang="en">
            <body className={inter.className}>
                <Header
                    setShowCart={setShowCart}
                    setFetchTrigger={setFetchTrigger}
                />
                <pageTriggerContext.Provider value={pageTrigger}>
                    <pageTriggerDispatch.Provider value={dispatch}>
                        <Cart
                            showCart={showCart}
                            setShowCart={setShowCart}
                            fetchTrigger={fetchTrigger}
                            setFetchTrigger={setFetchTrigger}
                        />
                        {children}
                    </pageTriggerDispatch.Provider>
                </pageTriggerContext.Provider>
                <Footer />
            </body>
        </html>
    );
}
